### ISSUE TITLE
strange query result

### ISSUE THREAD

**Issue by dripp1** [elastic/elasticsearch-analysis-stempel#44] opened 2015-06-14 15:37 UTC
Here is the issue:
1. Use the Polish analyzer to index a document that contains in one of the fields the text "SIERPOWY Baton Energia #girl weganskie cudo #girl"
2. run the following query:

```
{
  "from": 0,
  "size": 50,
  "query": {
    "bool": {
      "should": [
        {
          "match": {
            "_all": {
              "query": "value",
              "type": "boolean"
            }
          }
        }
      ]
    }
  },
  "highlight": {
    "pre_tags": [
      "<b>"
    ],
    "post_tags": [
      "</b>"
    ],
    "fragment_size": 0,
    "number_of_fragments": 0,
    "fields": {
      "*": {}
    }
  }
}
```

3. You expect not to find anything, because the word "value" is not in the text, but you get the record that you indexed above, with the word "girl" highlighted:

```
{
	"took" : 11,
	"timed_out" : false,
	"_shards" : {
		"total" : 170,
		"successful" : 165,
		"failed" : 0
	},
	"hits" : {
		"total" : 1,
		"max_score" : 0.13561106,
		"hits" : [{
				"_index" : "fts-polish",
				"_type" : "Document",
				"_id" : "bool2",
				"_score" : 0.13561106,
				"_source" : {
					"_analyzer" : "polish",
					"streamId" : 1,
					"language" : "Polish",
					"message" : "SIERPOWY Baton Energia #girl weganskie cudo #girl"
				},
				"highlight" : {
					"message" : [
						"SIERPOWY Baton Energia #<b>girl</b> weganskie cudo #<b>girl</b>"
					]
				}
			}
		]
	}
}
```

**Comment by dripp1** [comment] 2015-07-14 07:12
Anybody among the contributors to this plugin that could possibly comment on the above issue?
Thanks,
Doron

**Comment by dadoonet** [comment] 2015-08-27 15:54
Did you apply your analyzer to the `_all` field?
A full script would help to reproduce your problem and may be give you a better answer.

BTW, please consider using discuss.elastic.co for questions. More people will be able to answer and help!

**Comment by dripp1** [comment] 2015-08-30 05:29
I applied the Polish analyzer to the whole record indexed, by entering its name in the _analyzer field.
I will post this on discuss.elastic.co as well - thanks.

**Comment by dadoonet** [comment] 2015-08-30 07:30
As I said, without a script, it's hard to understand.

**Comment by dripp1** [comment] 2015-08-30 08:20
{
  "_source": {
    "streamId": "1",
    "language": "polish",
    "_analyzer": "polish",
    "message": "SIERPOWY 7:19 Baton Energia #girl weganskie cudo #girl"
  }
}

**Comment by dadoonet** [comment] 2015-08-30 08:30
What is that?

**Comment by dripp1** [comment] 2015-08-30 08:41
The record I indexed with the polish analyzer

**Comment by dadoonet** [comment] 2015-08-30 09:17
Ok. What should I understand?
What can I reproduce with that?

**Comment by dripp1** [comment] 2015-08-30 10:22
1. Install the Polish analyzer
2. Create an index in which the default_search is the Polish analyzer
3. Create the above record on that index. As the record _analyzer field contains "polish" - the Polish analyzer will do the indexing
4. Now run the query:
{
  "from": 0,
  "size": 50,
  "query": {
    "bool": {
      "should": [
        {
          "match": {
            "_all": {
              "query": "value",
              "type": "boolean"
            }
          }
        }
      ]
    }
  },
  "highlight": {
    "pre_tags": [
      "<b>"
    ],
    "post_tags": [
      "</b>"
    ],
    "fragment_size": 0,
    "number_of_fragments": 0,
    "fields": {
      "*": {}
    }
  }
}

on that index and see the results.

**Comment by dadoonet** [comment] 2015-08-30 11:19
Can you now create a script which does all the steps from step 2 ?

**Comment by dripp1** [comment] 2015-08-30 12:04
If you can provide a short example for what you mean by a "script" - then I can replace the relevant pieces with the appropriate code. I normally don't use scripts but I do everything with the Java API, including also index creation, mapping and configuration.

**Comment by dadoonet** [comment] 2015-08-30 12:37
Sure: https://github.com/elastic/elasticsearch-analysis-stempel/blob/master/CONTRIBUTING.md#bug-reports or https://www.elastic.co/help/

**Comment by dripp1** [comment] 2015-08-31 09:06
curl -XPUT localhost:9200/polish_index '{
	"settings" : {
		"analysis" : {
			"analyzer" : {
				"default_search" : {
					"type" : "polish"
				},
				"default" : {
					"type" : "polish"
				}
			}
		}
	}
    }'

    curl -XPUT localhost:9200/polish_index/Document/1 -d '{
     "_analyzer": "polish",
     "message": "SIERPOWY 7:19 Baton Energia #girl weganskie cudo #girl"
    }'

    curl -XGET localhost:9200/polish_index/Document/_search '{
      "query": {
        "bool": {
         "should": [
        {
          "match": {
            "_all": {
              "query": "value",
              "type": "boolean"
            }
           }
         }
       ]
     }
    },
      "highlight": {
        "pre_tags": [
          "<b>"
        ],
        "post_tags": [
         "</b>"
        ],
        "fragment_size": 0,
        "number_of_fragments": 0,
       "fields": {
        "*": {}
      }
     }
    }'

**Comment by dadoonet** [comment] 2015-08-31 10:18
@dripp1 Thank you for the full reproduction. It helps a lot!
I modified a bit your script and added the missing `-d`.

I'm getting your results as well.

From your script, I created a new one to find what is happening here:

```json
# Create an index with term_vectors
DELETE /polish_index
PUT /polish_index
{
  "mappings": {
    "Document": {
      "properties": {
        "message": {
          "analyzer": "polish",
          "type": "string", 
          "term_vector": "with_positions_offsets_payloads"
        }
      }
    }
  }
}

# Index one document
PUT /polish_index/Document/1
{
 "message": "SIERPOWY 7:19 Baton Energia #girl weganskie cudo #girl"
}

# Index a second document
PUT /polish_index/Document/2
{
 "message": "value"
}

# Get indexed terms for both docs
GET polish_index/Document/1/_termvector
GET polish_index/Document/2/_termvector
```

This gives a `ć` term for both docs:

```json
{
   "_index": "polish_index",
   "_type": "Document",
   "_id": "1",
   "_version": 1,
   "found": true,
   "took": 1,
   "term_vectors": {
      "message": {
         "field_statistics": {
            "sum_doc_freq": 8,
            "doc_count": 1,
            "sum_ttf": 9
         },
         "terms": {
            "7": {
               "term_freq": 1,
               "tokens": [
                  {
                     "position": 1,
                     "start_offset": 9,
                     "end_offset": 10
                  }
               ]
            },
            "19": {
               "term_freq": 1,
               "tokens": [
                  {
                     "position": 2,
                     "start_offset": 11,
                     "end_offset": 13
                  }
               ]
            },
            "baton": {
               "term_freq": 1,
               "tokens": [
                  {
                     "position": 3,
                     "start_offset": 14,
                     "end_offset": 19
                  }
               ]
            },
            "cudo": {
               "term_freq": 1,
               "tokens": [
                  {
                     "position": 7,
                     "start_offset": 44,
                     "end_offset": 48
                  }
               ]
            },
            "energia": {
               "term_freq": 1,
               "tokens": [
                  {
                     "position": 4,
                     "start_offset": 20,
                     "end_offset": 27
                  }
               ]
            },
            "sierpowa": {
               "term_freq": 1,
               "tokens": [
                  {
                     "position": 0,
                     "start_offset": 0,
                     "end_offset": 8
                  }
               ]
            },
            "weganski": {
               "term_freq": 1,
               "tokens": [
                  {
                     "position": 6,
                     "start_offset": 34,
                     "end_offset": 43
                  }
               ]
            },
            "ć": {
               "term_freq": 2,
               "tokens": [
                  {
                     "position": 5,
                     "start_offset": 29,
                     "end_offset": 33
                  },
                  {
                     "position": 8,
                     "start_offset": 50,
                     "end_offset": 54
                  }
               ]
            }
         }
      }
   }
}
```

```json
{
   "_index": "polish_index",
   "_type": "Document",
   "_id": "2",
   "_version": 1,
   "found": true,
   "took": 1,
   "term_vectors": {
      "message": {
         "field_statistics": {
            "sum_doc_freq": 1,
            "doc_count": 1,
            "sum_ttf": 1
         },
         "terms": {
            "ć": {
               "term_freq": 1,
               "tokens": [
                  {
                     "position": 0,
                     "start_offset": 0,
                     "end_offset": 5
                  }
               ]
            }
         }
      }
   }
}
```

That's the reason the following request matches:

```json
GET /polish_index/Document/_search
{
  "query": {
    "match": {
      "message": "value"
    }
  }
}
```

What I don't understand is why the _analyze endpoint produces something different:

```sh
curl -XPOST "http://localhost:9200/_analyze?analyzer=polish&pretty" -d "default"
```

```json
{
  "tokens" : [ {
    "token" : "default",
    "start_offset" : 0,
    "end_offset" : 7,
    "type" : "<ALPHANUM>",
    "position" : 0
  } ]
}
```

@rmuir @jpountz Do you have any idea?

**Comment by dripp1** [comment] 2015-08-31 12:54
Thank you for the explanation. I wonder why "ć" was extracted from seemingly unrelated characters and what can be done to overcome this.

**Comment by dripp1** [comment] 2015-09-02 05:13
See also: https://discuss.elastic.co/t/strange-query-result-with-the-polish-analyzer/28300/2

**Comment by dadoonet** [comment] 2015-09-02 06:00
Sounds like it's the same issue as seen at #31. 

@rmuir already [commented](https://github.com/elastic/elasticsearch-analysis-stempel/issues/31#issuecomment-54134582) that it's not an issue with the plugin or with the stempel Lucene module.

Closing then.

**Closed by dadoonet** 2015-09-02 06:00 UTC

**Comment by rmuir** [comment] 2015-09-02 06:39
I think a good solution would be to provide morfologik integration from lucene's analyzers/morfologik. Unfortunately this analyzer not going to work with ES 2.0 until this terrible terrible hack is removed first, moved to solr, made optional, something: https://github.com/apache/lucene-solr/blob/trunk/lucene/analysis/morfologik/src/java/org/apache/lucene/analysis/morfologik/MorfologikFilter.java#L80-L89
